version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cs2_market_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cs2_market
      POSTGRES_USER: cs2_user
      POSTGRES_PASSWORD: cs2_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: